import os
AWS_ACCESS_KEY_ID_SQS = os.environ.get('AWS_ACCESS_KEY_ID_SQS')
AWS_SECRET_ACCESS_KEY_SQS = os.environ.get('AWS_SECRET_ACCESS_KEY_SQS')
AWS_REGION_SQS = os.environ.get('AWS_REGION_SQS')
AWS_QUEUE_URL_IN = os.environ.get('AWS_QUEUE_URL_IN')
AWS_QUEUE_URL_OUT_CYPRESS = os.environ.get('AWS_QUEUE_URL_OUT_CYPRESS')
AWS_QUEUE_URL_OUT_ADB = os.environ.get('AWS_QUEUE_URL_OUT_ADB')
AWS_QUEUE_URL_OUT_CALABASH = os.environ.get('AWS_QUEUE_URL_OUT_CALABASH')
AWS_QUEUE_URL_OUT_VRT = os.environ.get('AWS_QUEUE_URL_OUT_VRT')
AWS_QUEUE_URL_OUT_MUTODE = os.environ.get('AWS_QUEUE_URL_OUT_MUTODE')
SLEEP_TIME = 10
